### PR TITLE
Remove scss/partial-no-import

### PR DESCRIPTION
**Pull request by tylerball**
As we move to ES6 we encourage explicit imports of dependencies in any given script. I think we should also encourage this for styles. If a CSS component has a dependency on another component shouldn't we be explicit about it?

cc @Shopify/fed

### CODE REVIEW

**Comment by beefchimi** [comment]
I love this - but how does the code magic work where styles are not included multiple times in the compiled code?

**Comment by lemonmade** [comment]
We went this way in Polaris but eventually walked it back. It ended up being problematic for a few reasons:

1. Any actual CSS will be duplicated
2. Any variables or functions will be redefined for each one, which is potentially problematic (it was for us because of some variables we have for things like whether the nav is visible
3. Builds take longer
4. Unlike JS imports, we have no indicator of imports that are no longer used, or functions that are missing their relevant imports, which means that tooling is not helping you write or maintain the styles

I like the idea but I am not sure that it makes sense given the limitations of Sass

**Comment by kaelig** [comment]
I agree with @lemonmade.

Thankfully, Sass 4 will have a proper module system and this issue will be solved by it.

**Comment by tylerball** [comment]
I totally thought sass was smart enough not to include the code twice! auuuuugh. I'll close.

**Pull request closed without merging**
